import * as z from "zod"

export const PostModel = z.object({
  /**
   * The unique identifier for the post
   * @default {Generated by database}
   */
  id: z.string().uuid(),
  /**
   * A brief title that describes the contents of the post
   */
  title: z.string().max(255, { message: "The title must be shorter than 256 characters" }),
  /**
   * The actual contents of the post.
   */
  contents: z.string().max(10240),
})

/**
 * Prisma Model Select Zod Schema
 *
 */

export const PostModelSelect = z.object({
  /**
   * The unique identifier for the post
   * @default {Generated by database}
   */
  id: z.boolean().optional(),
  /**
   * A brief title that describes the contents of the post
   */
  title: z.boolean().optional(),
  /**
   * The actual contents of the post.
   */
  contents: z.boolean().optional(),
})
